name: date_calc_lts
description: Updated Date manipulation library for Dart. It provides a class that inherits from the DateTime class, makes it easy to calculate additions, subtractions and so on.
version: 1.0.0+1
homepage: https://github.com/imsudip/date_calc

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  meta: ^1.3.0
  intl: ^0.17.0
dev_dependencies:
  test: ^1.17.10
